theme = "papercolor-light"

[editor]
bufferline = "multiple"
color-modes = true
cursorline = true
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.insert.j]
k = "normal_mode"

[keys.normal]
C-l = ":reload"

[keys.insert]
C-l = ":reload"
