#!/bin/bash

DOTFILES="$( cd "$( dirname "$0" )" && pwd )"
pushd $DOTFILES

for NAME in */_*; do

  BASENAME=${NAME##*/}
  DOTNAME=${BASENAME##_}

  ln -siv ${DOTFILES}/${NAME} ~/.${DOTNAME}

done

# Git helpers
git clone https://github.com/gmarik/vundle.git ${DOTFILES}/vim/_vim/bundle/vundle
sudo gem install git-smart

# SSH config still pending...

popd

