#!/usr/bin/env bash

CONFIG=$HOME/.config/nvim
DATA=$HOME/.local/share/nvim

mkdir -p $CONFIG/spell $CONFIG/autoload
mkdir -p $DATA/backup $DATA/undo

if [ ! -f $CONFIG/autoload/plug.vim ]; then
  curl -fLo $CONFIG/autoload/plug.vim \
            https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

nvim +"PlugSnapshot! $CONFIG/revert-plugupdate" +PlugUpgrade +PlugClean! +PlugUpdate +"silent TSUpdateSync"
