#!/usr/bin/env bash

CONFIG=$HOME/.config/nvim
DATA=$HOME/.local/share/nvim

mkdir -p $DATA/{backup,undo}

PLUGDIR=${DATA}/site/autoload
if [ ! -f $PLUGDIR/plug.vim ]; then
  echo "Downloading vim-plug..."
  curl -#fLo $PLUGDIR/plug.vim --create-dirs \
            https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

nvim +"PlugSnapshot! $CONFIG/revert-plugupdate" +PlugUpgrade +PlugClean! +PlugUpdate +"silent TSUpdateSync"
