icons = "awesome"

[[block]]
block = "disk_space"
path = "/"
alias = ""
info_type = "available"
unit = "GiB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "battery"
format = "{percentage}% ({time}@{power}W)"
interval = 10

[[block]]
block = "temperature"
collapsed = false
format = "{average}°"
interval = 5

[[block]]
block = "time"
interval = 10
format = "%a %d/%m %R"
