#!/usr/bin/env bash

if [ ! -f ~/.vim/autoload/plug.vim ]; then
  curl -fLo ~/.vim/autoload/plug.vim \
            https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

vim +PlugUpgrade +PlugClean! +PlugUpdate +"PlugSnapshot ~/.vim/revert-plugupdate" +qa

