#!/usr/bin/env bash

CONFIG=$HOME/.config/nvim

mkdir -p $CONFIG/undo $CONFIG/spell $CONFIG/autoload

if [ ! -f $CONFIG/autoload/plug.vim ]; then
  curl -fLo $CONFIG/autoload/plug.vim \
            https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

nvim +PlugUpgrade +PlugClean! +PlugUpdate +"PlugSnapshot! $CONFIG/revert-plugupdate" +qa
nvim +UpdateRemotePlugins +qa

